import { FormEvent, useState } from 'react';
import { Bot, MessageCircle, Send, X } from 'lucide-react';
import { api } from '../api/client';

type Message = { from: 'boom' | 'visitor'; text: string };
export function BoomChat() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ from: 'boom', text: 'Hi, I’m Boom — a friend of Bharath. Ask me about KBK Films services, booking, tracking, or deliveries.' }]);
  const send = async (event: FormEvent) => { event.preventDefault(); const text = input.trim(); if (!text || loading) return; setInput(''); setMessages(current => [...current, { from: 'visitor', text }]); setLoading(true); try { const result = await api.askBoom(text); setMessages(current => [...current, { from: 'boom', text: result.reply }]); } catch { setMessages(current => [...current, { from: 'boom', text: 'I’m having a short connection issue. Please try again or contact KBK Films directly.' }]); } finally { setLoading(false); } };
  return <div className="fixed z-50 bottom-5 right-5"><button aria-label="Open Boom chat" onClick={() => setOpen(!open)} className="ml-auto flex items-center gap-2 rounded-full bg-gold text-black font-bold shadow-xl px-5 py-3"><MessageCircle size={20} /> Ask Boom</button>{open && <section className="mt-3 w-[min(92vw,380px)] overflow-hidden rounded-2xl border border-gold/40 bg-[#10100f] shadow-2xl"><header className="flex items-center justify-between p-4 border-b border-gold/20"><span className="flex items-center gap-2 font-bold"><Bot className="text-gold" /> Boom <small className="font-normal text-ivory-400">friend of Bharath</small></span><button aria-label="Close" onClick={() => setOpen(false)}><X size={18} /></button></header><div className="h-72 overflow-y-auto p-4 space-y-3">{messages.map((message, index) => <p key={index} className={`max-w-[88%] rounded-2xl p-3 text-sm ${message.from === 'boom' ? 'bg-white/10 text-ivory-100' : 'bg-gold text-black ml-auto'}`}>{message.text}</p>)}{loading && <p className="text-xs text-ivory-400">Boom is thinking…</p>}</div><form onSubmit={send} className="flex gap-2 p-3 border-t border-gold/20"><input value={input} onChange={e => setInput(e.target.value)} maxLength={800} placeholder="Ask a question…" className="min-w-0 flex-1 rounded-xl bg-black/30 border border-white/15 px-3 py-2 text-sm" /><button className="rounded-xl bg-gold text-black p-2" aria-label="Send"><Send size={18} /></button></form></section>}</div>;
}
